plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.2-SNAPSHOT'
}

group = project.property('group')
version = project.property('version')
base.archivesName = project.property('modname')

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

import xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider


repositories {
    mavenLocal()
    mavenCentral()
    unimined.modrinthMaven()
    flatDir {
        dirs 'custom_jar'
    }
}

unimined {
    useGlobalCache = false

    minecraft {
        version 'b1.7.3'
        side "client"
        mods {
            modImplementation {
                // you can do this is mods have the wrong access widener mapping, but it may break runs
                catchAWNamespaceAssertion()
            }
        }

        mappings {
            retroMCP("b1.7")
            devNamespace("retroMCP")
            stubs(['official', 'retroMCP']) {
                def base = 'net/minecraft/src'
                def mapClass = { name ->
                    def path = "$base/$name"
                    c(name, path, path)
                }

                jarClasses(file('custom_jar/ModLoaderRecobbled-1.2.1.jar')).each(mapClass)
                jarClasses(file('custom_jar/recobbled-1.6_03.jar')).each(mapClass)
            }
        }

        MinecraftProvider minecraftProvider = delegate as MinecraftProvider

        runs {
            config("client") {
                javaVersion = JavaVersion.VERSION_1_8
                jvmArgs "-Dfabric.gameVersion=${mc.version}",
                        "-Dfabric.runtimeMappingNamespace=named"
            }
        }


        merged {
            fabric {
                loader '0.19.5'
                if(hasAccessWidener())
                    accessWidener(project.file("src/main/resources/" + project.property('access_widener')))
                customIntermediaries = true
                prodNamespace "official"
                devMappings = null
            }
            jarMod {
                enableJarModAgent = false
            }
        }
    }
}

dependencies {
    jarMod name: "recobbled", version: "1.6_03"
    modImplementation name: "ModLoaderRecobbled", version: "1.2.1"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(RemapJarTask).configureEach {
    mixinRemap {
        enableBaseMixin()
        enableMixinExtra()
    }

    doLast {
        if(hasAccessWidener())
            fixAccessWidener(archiveFile.get().asFile, temporaryDir)
    }
}

def hasAccessWidener() {
    return project.hasProperty('access_widener') && project.access_widener.length() > 0
}

import xyz.wagyourtail.unimined.api.minecraft.task.RemapJarTask

import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream

def fixAccessWidener(File jarFile, File temporaryDir) {
    def tempFile = new File(temporaryDir, jarFile.name + ".tmp")
    def awPath = project.property('access_widener')
    def input = new ZipFile(jarFile)
    def output = new ZipOutputStream(new FileOutputStream(tempFile))
    try {
        input.entries().each { entry ->
            def bytes = input.getInputStream(entry).bytes
            if (entry.name == awPath) {
                def text = new String(bytes, "UTF-8")
                text = text.replaceFirst("intermediary","official")
                bytes = text.getBytes("UTF-8")
            }
            def newEntry = new ZipEntry(entry.name)
            newEntry.time = entry.time
            newEntry.method = entry.method
            output.putNextEntry(newEntry)
            output.write(bytes)
            output.closeEntry()
        }
    } finally {
        output.close()
        input.close()
    }
    if (!jarFile.delete()) {
        throw new GradleException("Could not replace remapped jar: ${jarFile}")
    }
    if (!tempFile.renameTo(jarFile)) {
        throw new GradleException("Could not rename temporary jar to: ${jarFile}")
    }
}

def jarClasses(File file) {
    def zip = new ZipFile(file)
    def names = []

    try {
        zip.entries().each { entry ->
            if (entry.name.endsWith('.class') && !entry.name.contains('/')) {
                def name = entry.name - '.class'
                if (name.size() > 2) {
                    names << name
                }
            }
        }
    } finally {
        zip.close()
    }

    return names
}